server:
  port: 8081
spring:
  datasource:
    url: jdbc:h2:mem:Roomy
    driver-class-name: org.h2.Driver
    platform: h2
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
